import { platformBrowser } from '@angular/platform-browser';
import { enableProdMode } from '@angular/core';
//This is generated by runtime of "ngc" compiler
import { PayrollModuleNgFactory } from './aot/app.module.ngfactory';

enableProdMode();
platformBrowser().bootstrapModuleFactory(PayrollModuleNgFactory);
